name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  # Specify the .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish

      - name: Create zip file
        run: Compress-Archive -Path ./publish/* -DestinationPath ./publish/LocalAI-CLI.zip

      - name: Create Git Tag
        id: create_tag
        run: |
          tag_name=v1.0.0-$(date +'%Y%m%d%H%M%S')
          echo "tag_name=$tag_name" >> $GITHUB_ENV
          git tag $tag_name
          git push origin $tag_name
        shell: bash

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag_name }}
          release_name: 'Release ${{ env.tag_name }}'
          body: 'This release includes the latest changes.'
          draft: false
          prerelease: false

      - name: Upload Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/LocalAI-CLI.zip
          asset_name: LocalAI-CLI.zip
          asset_content_type: application/zip
