name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  # Specify the .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build projects
        run: dotnet build --configuration Release

      - name: Publish projects
        run: |
          $projects = Get-ChildItem -Filter *.csproj -Recurse
          foreach ($project in $projects) {
            dotnet publish $project.FullName --configuration Release -o ./publish/$($project.BaseName)
          }

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: 'Release ${{ github.ref }}'
          body: 'This release includes the latest changes.'
          draft: false
          prerelease: false

      - name: Upload Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish
          asset_name: myapp.zip
          asset_content_type: application/zip
